In [1]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
     'sekar']

In [16]:
voc_size=10000

## One Hot Representation

In [17]:
[one_hot(words,voc_size) for words in sent]

[[6813, 1246, 4907, 1070],
 [6813, 1246, 4907, 9483],
 [6813, 1795, 4907, 4625],
 [3724, 3731, 2514, 3101, 7010],
 [3724, 3731, 2514, 3101, 1024],
 [9810, 6813, 9638, 4907, 2193],
 [7353, 7698, 4319, 3101],
 [3443]]

In [18]:
ohe_repr=[one_hot(words,voc_size) for words in sent]

 ## Word Embedding Representation

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [23]:
sent_length=10

In [27]:
emedded_docs=pad_sequences(ohe_repr,padding='pre',maxlen=sent_length)

In [28]:
emedded_docs

array([[   0,    0,    0,    0,    0,    0, 6813, 1246, 4907, 1070],
       [   0,    0,    0,    0,    0,    0, 6813, 1246, 4907, 9483],
       [   0,    0,    0,    0,    0,    0, 6813, 1795, 4907, 4625],
       [   0,    0,    0,    0,    0, 3724, 3731, 2514, 3101, 7010],
       [   0,    0,    0,    0,    0, 3724, 3731, 2514, 3101, 1024],
       [   0,    0,    0,    0,    0, 9810, 6813, 9638, 4907, 2193],
       [   0,    0,    0,    0,    0,    0, 7353, 7698, 4319, 3101],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 3443]],
      dtype=int32)

In [29]:
pad_sequences(ohe_repr,padding='post',maxlen=sent_length)

array([[6813, 1246, 4907, 1070,    0,    0,    0,    0,    0,    0],
       [6813, 1246, 4907, 9483,    0,    0,    0,    0,    0,    0],
       [6813, 1795, 4907, 4625,    0,    0,    0,    0,    0,    0],
       [3724, 3731, 2514, 3101, 7010,    0,    0,    0,    0,    0],
       [3724, 3731, 2514, 3101, 1024,    0,    0,    0,    0,    0],
       [9810, 6813, 9638, 4907, 2193,    0,    0,    0,    0,    0],
       [7353, 7698, 4319, 3101,    0,    0,    0,    0,    0,    0],
       [3443,    0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [26]:
dim=10

In [30]:
model=Sequential()

In [31]:
model.add(Embedding(voc_size,10,input_length=sent_length))

In [32]:
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [36]:
emedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 6813, 1246, 4907, 1070],
      dtype=int32)

In [35]:
model.predict(emedded_docs[0])

1/1 [==============================] - 0s 84ms/step


array([[ 0.04973258,  0.01430338,  0.02647534, -0.01339277, -0.04593075,
         0.03295536,  0.01023068, -0.03441447,  0.0338526 ,  0.00219437],
       [ 0.04973258,  0.01430338,  0.02647534, -0.01339277, -0.04593075,
         0.03295536,  0.01023068, -0.03441447,  0.0338526 ,  0.00219437],
       [ 0.04973258,  0.01430338,  0.02647534, -0.01339277, -0.04593075,
         0.03295536,  0.01023068, -0.03441447,  0.0338526 ,  0.00219437],
       [ 0.04973258,  0.01430338,  0.02647534, -0.01339277, -0.04593075,
         0.03295536,  0.01023068, -0.03441447,  0.0338526 ,  0.00219437],
       [ 0.04973258,  0.01430338,  0.02647534, -0.01339277, -0.04593075,
         0.03295536,  0.01023068, -0.03441447,  0.0338526 ,  0.00219437],
       [ 0.04973258,  0.01430338,  0.02647534, -0.01339277, -0.04593075,
         0.03295536,  0.01023068, -0.03441447,  0.0338526 ,  0.00219437],
       [-0.04995466,  0.00613592,  0.02863672, -0.00298036, -0.04239578,
         0.04127694,  0.02681794,  0.03730457

In [37]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

## Provide the Vocab_Size

In [38]:
voc_size=10000

## One Hot Representation

In [41]:
from tensorflow.keras.preprocessing.text import one_hot

In [39]:
ohe_repr=[one_hot(words,voc_size) for words in sent]

In [40]:
ohe_repr

[[6813, 6066, 1045, 2514, 8414, 4463],
 [7069, 2930, 1045, 5309, 4779, 4354],
 [3724, 5473, 5583, 3780],
 [6813, 4163, 1045, 8832, 6813, 2464],
 [4491, 7886, 9736, 1045, 5309, 4779, 4354],
 [7875, 1045, 5309, 4779, 8970, 327]]

## Word Embedding Representation

In [42]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [43]:
sent_length=12

In [44]:
emedded_docs=pad_sequences(ohe_repr,padding='pre',maxlen=sent_length)

In [45]:
dim=10

In [46]:
model=Sequential()

In [47]:
model.add(Embedding(voc_size,10,input_length=sent_length))

In [48]:
model.compile('adam','mse')

In [49]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 12, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
emedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 6813, 6066, 1045, 2514, 8414,
       4463], dtype=int32)

In [51]:
model.predict(emedded_docs[0])

1/1 [==============================] - 0s 26ms/step


array([[-0.01213616,  0.04154095,  0.02756781, -0.01345231, -0.03191205,
         0.01435051, -0.02867824, -0.0444105 , -0.03310736,  0.01583575],
       [-0.01213616,  0.04154095,  0.02756781, -0.01345231, -0.03191205,
         0.01435051, -0.02867824, -0.0444105 , -0.03310736,  0.01583575],
       [-0.01213616,  0.04154095,  0.02756781, -0.01345231, -0.03191205,
         0.01435051, -0.02867824, -0.0444105 , -0.03310736,  0.01583575],
       [-0.01213616,  0.04154095,  0.02756781, -0.01345231, -0.03191205,
         0.01435051, -0.02867824, -0.0444105 , -0.03310736,  0.01583575],
       [-0.01213616,  0.04154095,  0.02756781, -0.01345231, -0.03191205,
         0.01435051, -0.02867824, -0.0444105 , -0.03310736,  0.01583575],
       [-0.01213616,  0.04154095,  0.02756781, -0.01345231, -0.03191205,
         0.01435051, -0.02867824, -0.0444105 , -0.03310736,  0.01583575],
       [ 0.01647336, -0.04895823, -0.03419895, -0.02570728, -0.04277211,
         0.03287378, -0.03375705, -0.02497561