<a href="https://colab.research.google.com/github/vallirajasekar/NLP_Learning/blob/main/Day_5_word_2_vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gensim

In [ ]:
from gensim.models import Word2Vec,keyedvectors

In [ ]:
import gensim.downloader as api

In [ ]:
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
wv['Kings']

array([-3.73535156e-02, -1.17187500e-01, -1.16210938e-01,  2.98828125e-01,
       -4.66308594e-02, -1.51367188e-01, -1.94335938e-01,  2.86865234e-02,
       -6.54296875e-02,  1.59179688e-01,  5.73730469e-02,  5.35156250e-01,
       -5.78613281e-02,  3.35937500e-01, -1.39648438e-01, -3.32031250e-01,
       -8.83789062e-02,  8.54492188e-02, -6.88476562e-02,  3.53515625e-01,
        1.39648438e-01,  7.91015625e-02, -6.82830811e-04, -2.35351562e-01,
       -1.68457031e-02,  1.26953125e-01, -1.91650391e-02, -1.49414062e-01,
        1.70898438e-01, -1.47460938e-01, -9.37500000e-02, -1.08398438e-01,
       -2.23388672e-02,  3.00781250e-01, -9.03320312e-02,  2.77343750e-01,
        4.82421875e-01, -7.99560547e-03, -3.22265625e-01,  7.66601562e-02,
       -1.39770508e-02, -4.49218750e-01, -2.07031250e-01, -3.80859375e-02,
        1.52343750e-01,  6.44531250e-02,  4.15039062e-02, -1.66015625e-01,
        5.31005859e-03,  3.63281250e-01,  2.01416016e-02,  2.94921875e-01,
        2.18750000e-01, -

In [ ]:
wv['sachin']

array([-2.37304688e-01,  6.12792969e-02,  1.58203125e-01,  3.65234375e-01,
        3.78417969e-02, -1.17187500e-01,  2.34375000e-01, -2.55859375e-01,
        1.58203125e-01, -1.00585938e-01, -7.47070312e-02, -2.46093750e-01,
        1.37695312e-01,  1.92382812e-01,  4.85839844e-02,  2.25585938e-01,
        1.84570312e-01,  5.24902344e-02,  2.78320312e-02,  2.99072266e-02,
       -2.00195312e-01, -1.86523438e-01,  2.59765625e-01, -2.94921875e-01,
       -1.16699219e-01,  2.30712891e-02, -2.98828125e-01, -1.59912109e-02,
        2.33398438e-01, -2.31445312e-01, -6.17675781e-02,  1.57226562e-01,
       -1.57226562e-01,  4.78515625e-02, -4.60937500e-01,  8.05664062e-02,
       -2.50000000e-01,  4.10156250e-02,  2.07031250e-01,  1.83593750e-01,
        2.57812500e-01, -5.15136719e-02,  2.77343750e-01,  2.71484375e-01,
        1.96289062e-01, -7.95898438e-02, -2.69775391e-02, -2.81250000e-01,
       -5.51757812e-02, -1.10351562e-01, -2.23632812e-01,  5.34667969e-02,
        6.68945312e-02, -

In [ ]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [ ]:
wv.most_similar('sachin')

[('tendulkar', 0.7856917381286621),
 ('ganguly', 0.7785738706588745),
 ('sehwag', 0.7773319482803345),
 ('dravid', 0.7691141366958618),
 ('sachin_tendulkar', 0.741614580154419),
 ('laxman', 0.7271499037742615),
 ('KrisSrikkanth_says', 0.6995106339454651),
 ('murali', 0.6993196606636047),
 ('afridi', 0.6891643404960632),
 ('odi', 0.6883801817893982)]

In [ ]:
wv.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [ ]:
wv.most_similar('chennai')

[('pune', 0.6712838411331177),
 ('india', 0.667550265789032),
 ('delhi', 0.6614565849304199),
 ('hyderabad', 0.6592930555343628),
 ('mumbai', 0.6436912417411804),
 ('kolkata', 0.6362491250038147),
 ('kerala', 0.6332582235336304),
 ('orissa', 0.6280592679977417),
 ('rahul', 0.6232461333274841),
 ('bombay', 0.6189700961112976)]

In [ ]:
wv.most_similar('pune')

[('chennai', 0.6712837815284729),
 ('bombay', 0.6688694953918457),
 ('lucknow', 0.6641979217529297),
 ('orissa', 0.6586176156997681),
 ('hyderabad', 0.6568223237991333),
 ('suresh', 0.6354721188545227),
 ('Pune', 0.6296120882034302),
 ('kolkata', 0.6280205845832825),
 ('kerala', 0.6263408660888672),
 ('sharma', 0.6253863573074341)]

In [ ]:
wv.most_similar('goa')

[('tym', 0.5401601195335388),
 ('issa', 0.5395323634147644),
 ('4rm', 0.5348882675170898),
 ('lyk', 0.5190958380699158),
 ('malouda', 0.5182464718818665),
 ('saha', 0.5157965421676636),
 ('bahar', 0.5141395330429077),
 ('mikel', 0.5141184329986572),
 ('wayne_rooney', 0.5109692215919495),
 ('bhala', 0.5100680589675903)]

In [ ]:
wv.most_similar('Data')

[('data', 0.7262316346168518),
 ('Termed_Massively_Parallel', 0.5460323691368103),
 ('Data_System_IPEDS', 0.5428394079208374),
 ('Temperature_Maps', 0.5223192572593689),
 ('Analytics_Solution', 0.49304071068763733),
 ('Database', 0.4912521541118622),
 ('Partition_Master', 0.48701369762420654),
 ('QuickStudy', 0.48598507046699524),
 ('Geospatial_Data', 0.4815930426120758),
 ('Tweet_Sentiments_web', 0.4777469038963318)]

In [ ]:
wv.similarity('man','king')

0.22942673

In [ ]:
wv.similarity('man','women')

0.2883053

In [ ]:
wv['new']=wv['king']-wv['man']+wv['girl']

In [ ]:
wv.most_similar(['new'])

[('king', 0.765661358833313),
 ('queen', 0.6720073819160461),
 ('princess', 0.6519676446914673),
 ('prince', 0.5718944668769836),
 ('monarch', 0.5569813847541809),
 ('girl', 0.5426682829856873),
 ('princesses', 0.5278744101524353),
 ('crown_prince', 0.5183970332145691),
 ('kings', 0.5110754370689392),
 ('Prince_Paras', 0.5017852783203125)]

In [ ]:
wv['new']=wv['dhoni']-wv['pant']+wv['rohit']

In [ ]:
wv.most_similar(['new'])

[('dhoni', 0.6786987781524658),
 ('Paranavithana', 0.4654320478439331),
 ('sehwag', 0.43938130140304565),
 ('rohit', 0.43875885009765625),
 ('Hershelle_Gibbs', 0.4352143406867981),
 ('Binod_Das', 0.43478283286094666),
 ('Jayasuria', 0.4296184778213501),
 ('Tilakaratne_Dilshan', 0.42785146832466125),
 ('Gaafu_Dhaalu_atoll', 0.4273207187652588),
 ('Hashan_Tillekeratne', 0.4255143404006958)]

In [ ]:
wv.most_similar(['pant'])

[('trouser', 0.641515851020813),
 ('pants', 0.6320861577987671),
 ('leggings', 0.6175554990768433),
 ('jeans', 0.6117405891418457),
 ('bootcut', 0.6107251644134521),
 ('trousers', 0.6067577600479126),
 ('denims', 0.6040917038917542),
 ('denim_trousers', 0.6009911298751831),
 ('maxi_skirt', 0.6007580757141113),
 ('camis', 0.6002790927886963)]

In [ ]:
wv.most_similar(['modi'])

[('new', 0.8348628282546997),
 ('sonia', 0.6801087260246277),
 ('gandhi', 0.6775892972946167),
 ('advani', 0.6774588823318481),
 ('amit', 0.67608642578125),
 ('bjp', 0.6753196716308594),
 ('rahul', 0.6738477349281311),
 ('bihar', 0.6723117828369141),
 ('nitish', 0.6692695617675781),
 ('lalu', 0.6649435758590698)]

In [ ]:
wv.most_similar(['CSK'])

[('new', 0.506889283657074),
 ('Knight_Riders', 0.5064428448677063),
 ('Royal_Challengers', 0.5005569458007812),
 ('Super_Kings', 0.4971355199813843),
 ('Kings_XI_Punjab', 0.4944312870502472),
 ('CSK_Auto', 0.49398452043533325),
 ('Delhi_Daredevils', 0.4888964295387268),
 ('Deccan_Chargers', 0.48345622420310974),
 ('Kings_XI', 0.48306694626808167),
 ('Rajasthan_Royals', 0.48161381483078003)]

## Coding Part


In [9]:
import pandas as pd
import numpy as np

In [10]:
df=pd.read_csv('/content/spam.csv',)

In [11]:
df.drop(['Unnamed: 2','Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)

In [12]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
df.rename({'v1':'label','v2':'message'},axis=1,inplace=True)

In [19]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
import nltk

In [16]:
df.shape

(5572, 2)

In [17]:
import re

In [18]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [22]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [23]:
ps = PorterStemmer()
corpus = []

for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review = review.lower()
    review = review.split()

    # Use stopwords.words('english') to get the list of English stopwords
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [25]:
corpus[:5]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though']

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
cv=CountVectorizer(max_features=25000)

In [30]:
X=cv.fit_transform(corpus).toarray()

In [31]:
y=pd.get_dummies(df['label'])
y=y.iloc[:,1].values

In [32]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [37]:
y_pred=spam_detect_model.predict(X_test)

In [39]:
from sklearn.metrics import classification_report

In [41]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       949
           1       0.95      0.87      0.91       166

    accuracy                           0.97      1115
   macro avg       0.96      0.93      0.95      1115
weighted avg       0.97      0.97      0.97      1115



In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
tv=TfidfVectorizer()

In [44]:
X=tv.fit_transform(corpus).toarray()

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [46]:
from sklearn.linear_model import LogisticRegression


In [48]:
logisticR=LogisticRegression()


In [49]:
logisticR.fit(X_train, y_train)

LogisticRegression()

In [50]:
y_pred2 = logisticR.predict(X_test)


In [54]:
cm2 = classification_report(y_test, y_pred2)
print(cm2)


              precision    recall  f1-score   support

           0       0.95      1.00      0.98       949
           1       0.99      0.72      0.84       166

    accuracy                           0.96      1115
   macro avg       0.97      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115



## Word 2 Vec Implementation


In [55]:
from gensim.utils import simple_preprocess

In [57]:
from nltk import sent_tokenize

In [56]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [59]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [60]:
words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))



In [62]:
words[:5]

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though']]

In [64]:
import gensim

In [66]:
from gensim.models import Word2Vec

model = Word2Vec(words, window=5, min_count=2)

In [68]:
model.wv.index_to_key[:5]

['call', 'go', 'get', 'ur', 'gt']

In [69]:
model.corpus_count

5564

In [70]:
model.epochs

5

In [71]:
model.wv.similar_by_word('price')

[('phone', 0.9991462230682373),
 ('text', 0.9990825057029724),
 ('get', 0.9990633130073547),
 ('play', 0.9990501403808594),
 ('game', 0.9990464448928833),
 ('send', 0.9990408420562744),
 ('msg', 0.9990399479866028),
 ('win', 0.9990329146385193),
 ('work', 0.9990264773368835),
 ('even', 0.9990251064300537)]